### ISSUE TITLE
Помогите!!!

### ISSUE THREAD

**Issue by Anemicman** [NC22/webMCR#88]
Когда кто то регистрируется им выдаёт ошибку Registration is blocked. Used auth script from main CMS как это решить???

**Comment by CodersGit** [comment]
Это не ошибка. Регистрироваться нельзя если webMCR была установлена в режиме совместимости. Только через основной движок.

**Comment by Anemicman** [comment]
А это как можеш по скайпу обьяснить???мой скайп andrey.vorkunov1

**Comment by CodersGit** [comment]
Что там объяснять?

**Comment by Anemicman** [comment]
я непонел это как???

**Comment by Anemicman** [comment]
устанавливать как

**Comment by CodersGit** [comment]
Регистрация отключена потому что ты установил помимо webMCR еще DLE, XenForo или IPB. Регистрироваться в этом случае только через них.

**Comment by Anemicman** [comment]
ааа
