### ISSUE TITLE
будут ли обновы?

### ISSUE THREAD

**Issue by Eqiliux** [NC22/webMCR#92]
привет
webmcr reloaded перестал поддерживаться, будут ли новые версии здесь?

**Comment by CodersGit** [comment]
Нет, не будут.

**Comment by IncFree** [comment]
@CodersGit а почему не будут если не секрет?)

**Comment by NC22** [comment]
@IncFree автор сменил [хобби](http://nradiowave.tumblr.com/), а вот на работе просто нет времени заниматься еще и открытыми проектами достаточно времени. Да и так ли актуально это сейчас? Вроде никто особо не возражал и не просил вернуться к проекту 4 года назад)

**Comment by CodersGit** [comment]
@NC22 в общем-то, я так и думал) Удачи тебе в новых начинаниях ;)
@IncFree Мне, если честно, в принципе интересно как можно ворошить майн до сих пор. Я не думаю, что интерес народа еще жив к игре настолько, чтобы новые проекты хоть как-то окупались...

**Comment by CodersGit** [comment]
@NC22 кстати, к тебе не было просьб вернуться? По-моему, были. Но народ как-то в этом плане быстро перешел на WebMCR Reloaded и webMCRex, но до этого на рубакките по-моему ждали и твоего возвращения)
Энивей, когда я закрыл webMCRex народ писал мне с просьбами продолжить разработку. Раз и @qexyorg как-то забросил и свой движок, то и неудивительно что народ вспомнил и вернулся к тебе как к автору первого популярного движка.

**Comment by qexyorg** [comment]
WebMCR Reloaded не заброшен, а приостановлен. Т.к. помимо оф. работы, еще и свои проекты.
